num1=int(input("Enter the first number:"))
num2=int(input("Enter the second number:"))
print("The addition of",num1,"and",num2,"is:",num1+num2)
print("The subtraction of",num1,"and",num2,"is:",num1-num2)
print("The multiplication of",num1,"and",num2,"is:",num1*num2)
print("The division of",num1,"and",num2,"is:",num1/num2)
print("The floor division of",num1,"and",num2,"is:",num1//num2)
print("The exponent of",num1,"and",num2,"is:",num1**num2)
print("The mod of",num1,"and",num2,"is:",num1%num2)